
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 15 12:26:42 CDT 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 4;
  public static final int Parentesis_c = 13;
  public static final int Parentesis_a = 12;
  public static final int Suma = 8;
  public static final int Numero = 20;
  public static final int ERROR = 21;
  public static final int Identificador = 19;
  public static final int Int = 2;
  public static final int Llave_c = 15;
  public static final int Llave_a = 14;
  public static final int P_coma = 17;
  public static final int Main = 16;
  public static final int EOF = 0;
  public static final int Division = 11;
  public static final int Resta = 9;
  public static final int If = 3;
  public static final int Linea = 6;
  public static final int error = 1;
  public static final int Punto = 18;
  public static final int Igual = 7;
  public static final int While = 5;
  public static final int Multiplicacion = 10;
}

